version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qy make gcc libtool autoconf automake bison libreadline-dev

      - run:
          name: Autotools
          command: |
            libtoolize -qi
            autoreconf

      - run:
          name: Configure
          command: ./configure --with-readline

      - run:
          name: Build
          command: make 'ADDCFLAGS=-DGCDEBUG=1 -DREF_ASSERTIONS=1'

      - run:
          name: Trip
          command: make trip

      - persist_to_workspace:
        root: .
        paths:
          - es

  test:
    docker:
      - image: cimg/base:stable

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Test
          command: |
            mkdir -p ./test/results
            ./es -s < ./test/circleci.es ./test/run-tests.es ./test/tests/* > ./test/results/results.xml

      - store_test_results:
          path: ./test/results/


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
